### ISSUE TITLE
RubyMine displays "Cannot parse first-keystroke.." error on startup

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-jetbrains-editors#6]
See: https://github.com/pivotal/pivotal_ide_prefs/issues/24

**Comment by LukeWinikates** [comment]
Sounds like this is fixed on `pivotal_ide_prefs`'s master branch. Is there anything left to do here, maybe a way that we could make troubleshooting easier?

**Comment by aramprice** [comment]
Seems resolved, I only cross posted here for visibility.
